import styled from "styled-components";

export const ToggleButton = styled.button`
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 30px;
  height: 30px;
  margin-left: 1em;
  background-color: ${({ theme }) => theme.text};
  color: ${({ theme }) => theme.body};
  border: none;
  border-radius: 25px;
  cursor: pointer;
  position: relative;
  transition: all 0.4s ease-in-out;
  box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);

  &.rotate-center {
    -webkit-animation: rotate-center 1s cubic-bezier(0.5, 0, 0.5, 1) infinite alternate;
    animation: rotate-center 1s cubic-bezier(0.5, 0, 0.5, 1) infinite alternate;
  }

  /* ----------------------------------------------
  * Generated by Animista on 2022-12-26 12:13:3
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation rotate-center
   * ----------------------------------------
   */
  @-webkit-keyframes rotate-center {
    0% {
      -webkit-transform: rotate(4deg);
      transform: rotate(4deg);
    }

    100% {
      -webkit-transform: rotate(-4deg);
      transform: rotate(-4deg);
    }
  }

  @keyframes rotate-center {
    0% {
      -webkit-transform: rotate(4deg);
      transform: rotate(4deg);
    }

    100% {
      -webkit-transform: rotate(-4deg);
      transform: rotate(-4deg);
    }
  }

  svg {
    font-size: 1.8em;
  }

  @media only screen and (max-width: 1000px) {
    position: absolute;
    top: 0;
    right: 0;
    margin: 1em;
  }
`;